# Agentic Trek - Default Configuration

# Game Settings
game:
  difficulty: normal  # easy, normal, hard, expert
  mission_duration: 30.0  # Stardates
  random_seed: null  # Set to integer for reproducible games
  auto_save: true
  save_interval: 300  # seconds

# Galaxy Generation
galaxy:
  total_klingons: 15
  total_starbases: 4
  star_density: 0.3  # 0.0 to 1.0
  klingon_density: 0.2  # 0.0 to 1.0
  galaxy_size: 8  # 8x8 quadrants
  quadrant_size: 8  # 8x8 positions per quadrant

# Ship Configuration
ship:
  max_energy: 3000
  max_shields: 1500
  max_torpedoes: 10
  energy_regeneration: 0  # Energy per turn
  shield_efficiency: 1.0  # Shield absorption rate
  damage_threshold: 0.8  # System damage threshold

# AI Configuration
ai:
  # Klingon AI Settings
  klingon:
    base_aggression: 0.7  # 0.0 to 1.0
    learning_rate: 0.1  # How fast AI adapts
    tactical_awareness: 0.8  # Tactical decision quality
    adaptation_enabled: true
    base_health: 100
    base_energy: 200
    personality_distribution:
      aggressive: 0.3
      defensive: 0.2
      tactical: 0.2
      berserker: 0.15
      commander: 0.15
  
  # Strategic AI Settings
  strategic:
    planning_depth: 3  # Turns to look ahead
    risk_tolerance: 0.5  # 0.0 conservative, 1.0 aggressive
    optimization_enabled: true
    advice_frequency: 0.1  # Chance per turn to give advice
    
  # Difficulty Scaling
  difficulty_scaling:
    easy:
      klingon_health_multiplier: 0.7
      klingon_aggression_multiplier: 0.6
      player_damage_multiplier: 1.3
    normal:
      klingon_health_multiplier: 1.0
      klingon_aggression_multiplier: 1.0
      player_damage_multiplier: 1.0
    hard:
      klingon_health_multiplier: 1.3
      klingon_aggression_multiplier: 1.2
      player_damage_multiplier: 0.8
    expert:
      klingon_health_multiplier: 1.5
      klingon_aggression_multiplier: 1.4
      player_damage_multiplier: 0.7

# Interface Settings
interface:
  ascii:
    use_colors: true
    screen_width: 80
    command_history_size: 50
    auto_clear_screen: false
    
  pygame:
    window_width: 1024
    window_height: 768
    fullscreen: false
    fps: 60
    vsync: true
    sound_enabled: true
    music_enabled: true
    particle_effects: true

# Combat System
combat:
  phaser_max_range: 8.0
  torpedo_max_range: 10.0
  phaser_accuracy_base: 0.8
  torpedo_accuracy_base: 0.6
  damage_variance: 0.2  # Random damage variation
  critical_hit_chance: 0.1
  critical_hit_multiplier: 2.0

# Event System
events:
  random_event_chance: 0.05  # Per turn
  event_types:
    - solar_storm
    - space_anomaly
    - distress_call
    - klingon_reinforcements
    - starbase_emergency
  
  solar_storm:
    energy_drain: 200
    duration: 3  # turns
    
  space_anomaly:
    navigation_disruption: true
    sensor_interference: 0.5

# Performance Settings
performance:
  ai_thinking_time: 0.5  # seconds
  animation_speed: 1.0
  auto_optimization: true
  memory_cleanup_interval: 100  # turns

# Logging Configuration
logging:
  level: INFO  # DEBUG, INFO, WARNING, ERROR
  file: logs/trek.log
  max_size: 10MB
  backup_count: 5
  game_events_log: logs/game_events.log
  ai_decisions_log: logs/ai_decisions.log
  performance_log: logs/performance.log

# Development Settings
development:
  debug_mode: false
  show_ai_thinking: false
  god_mode: false  # Unlimited resources
  fast_time: false  # Accelerated time
  skip_intro: false
